apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: labelme
  namespace: default
spec:
  storageClassName: nfs-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi